[project]
name = "focusflow"
version = "1.0.0"
description = "Pomodoro timer with tasks and Premium subscription"
requires-python = ">=3.10"
dependencies = [
    "flet==0.85.3",
    "sqlalchemy>=2.0",
]

[tool.flet]
org = "com.k0teu4"
product = "FocusFlow"
version = "1.0.0"
build = 1

[tool.flet.app]
exclude = [
    ".git",
    ".venv",
    ".github",
    "__pycache__",
    "db/focusflow.db",
    "test_full_app.py",
    "test_csv_export.py",
    "test_sounds.py",
    "README.md",
]

[tool.flet.splash]
color = "#08033D"
dark_color = "#08033D"

[tool.flet.boot_screen.flet]
theme_mode = "dark"
bgcolor_dark = "#08033D"
spinner_color_dark = "#FECCE7"
spinner_size = 40
text_color_dark = "#FFFFFF"
prepare_message = "Подготовка приложения…"
startup_message = "Запуск…"
fade_out_duration = 300

[tool.flet.android]
permissions = [
    "android.permission.INTERNET",
    "android.permission.VIBRATE",
]
min_sdk = 24
target_sdk = 34